//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int id { get; set; }
        public string userEmail { get; set; }
        public string operation { get; set; }
        public string olddata { get; set; }
        public string newdata { get; set; }
        public string datetime { get; set; }
    }
}
