//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class C103audio
    {
        public int ID { get; set; }
        public Nullable<int> cable { get; set; }
        public string src_loc { get; set; }
        public string src_equip { get; set; }
        public string src_conn { get; set; }
        public string sh1 { get; set; }
        public string type { get; set; }
        public string mult_pair { get; set; }
        public string lnth { get; set; }
        public string signal { get; set; }
        public string dst_loc { get; set; }
        public string dst_equip { get; set; }
        public string dst_conn { get; set; }
        public string sh2 { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> chng { get; set; }
        public string order_num { get; set; }
        public string append_fr { get; set; }
        public Nullable<System.DateTime> append_dat { get; set; }
        public Nullable<int> feet { get; set; }
        public string lbl_size { get; set; }
        public string C_dbaselock { get; set; }
    }
}
