//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cablesold
    {
        public int CableID { get; set; }
        public int SrcEquipmentID { get; set; }
        public string SrcPort { get; set; }
        public int SrcConnectorTypeID { get; set; }
        public string SrcDrawingCode { get; set; }
        public int DestEquipmentID { get; set; }
        public string DestPort { get; set; }
        public int DestConnectorTypeID { get; set; }
        public string DestDrawingCode { get; set; }
        public int CableTypeID { get; set; }
        public string Color { get; set; }
        public int Length { get; set; }
        public string Detail { get; set; }
        public string Revision { get; set; }
        public string LastUpdatedBy { get; set; }
        public string LastUpdateDate { get; set; }
        public int CableCode { get; set; }
        public string Comments { get; set; }
        public string Signal { get; set; }
        public Nullable<bool> SrcShield { get; set; }
        public Nullable<bool> DestShield { get; set; }
        public string CableDetail { get; set; }
        public string SrcHostName { get; set; }
        public string SrcIPAddress { get; set; }
        public string DestHostName { get; set; }
        public string DestIPAddress { get; set; }
        public string SubRevision { get; set; }
        public string SrcMake { get; set; }
        public string SrcModel { get; set; }
        public string DestMake { get; set; }
        public string DestModel { get; set; }
        public string Panel { get; set; }
        public string Circuit { get; set; }
        public string PDU { get; set; }
        public double MaxPower { get; set; }
        public string ActionItem { get; set; }
    }
}
