//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class castlist
    {
        public int Id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Specify_number { get; set; }
        public string Show_name { get; set; }
        public string Type_of_Show { get; set; }
        public string AppearedIn { get; set; }
        public string Role_played { get; set; }
        public Nullable<int> Credit { get; set; }
    }
}
