//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColorType
    {
        public ColorType()
        {
            this.GroupingColors = new HashSet<GroupingColor>();
            this.SportColors = new HashSet<SportColor>();
            this.TeamColors = new HashSet<TeamColor>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GroupingColor> GroupingColors { get; set; }
        public virtual ICollection<SportColor> SportColors { get; set; }
        public virtual ICollection<TeamColor> TeamColors { get; set; }
    }
}
