//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageType
    {
        public ImageType()
        {
            this.GroupingImages = new HashSet<GroupingImage>();
            this.SportImages = new HashSet<SportImage>();
            this.TeamImages = new HashSet<TeamImage>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<GroupingImage> GroupingImages { get; set; }
        public virtual ICollection<SportImage> SportImages { get; set; }
        public virtual ICollection<TeamImage> TeamImages { get; set; }
    }
}
