//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int SportID { get; set; }
        public string Code { get; set; }
        public string NameLong { get; set; }
        public string NameShort { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string HivePrefix { get; set; }
        public Nullable<int> GroupingTypeId { get; set; }
    }
}
