//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeoCableMsEntities : DbContext
    {
        public NeoCableMsEntities()
            : base("name=NeoCableMsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PrintJob> PrintJobs { get; set; }
        public DbSet<C103audio> C103audio { get; set; }
        public DbSet<C103ctrl> C103ctrl { get; set; }
        public DbSet<C103video> C103video { get; set; }
        public DbSet<Audit> Audits { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<Buildings1> Buildings1 { get; set; }
        public DbSet<Cable> Cables { get; set; }
        public DbSet<Cablesold> Cablesolds { get; set; }
        public DbSet<CableType> CableTypes { get; set; }
        public DbSet<CableTypesold> CableTypesolds { get; set; }
        public DbSet<castlist> castlists { get; set; }
        public DbSet<ConnectorType> ConnectorTypes { get; set; }
        public DbSet<ConnectorTypesold> ConnectorTypesolds { get; set; }
        public DbSet<Equipment> Equipments { get; set; }
        public DbSet<Equipmentsold> Equipmentsolds { get; set; }
        public DbSet<EquipmentType> EquipmentTypes { get; set; }
        public DbSet<EquipmentTypes1> EquipmentTypes1 { get; set; }
        public DbSet<Missing_Cables> Missing_Cables { get; set; }
        public DbSet<Nebaud> Nebauds { get; set; }
        public DbSet<Nebctl> Nebctls { get; set; }
        public DbSet<Nebctl2> Nebctl2 { get; set; }
        public DbSet<Nebvid> Nebvids { get; set; }
        public DbSet<Rack> Racks { get; set; }
        public DbSet<Racksold> Racksolds { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Rooms1> Rooms1 { get; set; }
        public DbSet<Totalaud> Totalauds { get; set; }
        public DbSet<Totalctl> Totalctls { get; set; }
        public DbSet<Totaljet> Totaljets { get; set; }
        public DbSet<Totalvid> Totalvids { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
