//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms1
    {
        public int RoomID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public int BuildingID { get; set; }
    }
}
