//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int ID { get; set; }
        public Nullable<int> SportID { get; set; }
        public Nullable<int> LeagueID { get; set; }
        public Nullable<int> SourceTeamID { get; set; }
        public string Abbreviation { get; set; }
        public string DisplayAbbreviation { get; set; }
        public string City { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string CityAndState { get; set; }
        public string Stadium { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Surface { get; set; }
        public Nullable<bool> Dome { get; set; }
        public Nullable<short> Ranking { get; set; }
        public Nullable<short> Wins { get; set; }
        public Nullable<short> Losses { get; set; }
        public Nullable<short> Ties { get; set; }
        public string Logo { get; set; }
        public string Country { get; set; }
        public string CountryCode { get; set; }
        public string StatsIncAbbreviation { get; set; }
        public string OptaAbbreviation { get; set; }
    }
}
