//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamColor
    {
        public int ID { get; set; }
        public string HEX { get; set; }
        public string RGB { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public bool Hidden { get; set; }
    
        public virtual ColorType ColorType { get; set; }
    }
}
