//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportsDataQAEntities : DbContext
    {
        public SportsDataQAEntities()
            : base("name=SportsDataQAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ColorType> ColorTypes { get; set; }
        public DbSet<GroupingColor> GroupingColors { get; set; }
        public DbSet<GroupingImage> GroupingImages { get; set; }
        public DbSet<GroupingType> GroupingTypes { get; set; }
        public DbSet<ImageType> ImageTypes { get; set; }
        public DbSet<League> Leagues { get; set; }
        public DbSet<SportColor> SportColors { get; set; }
        public DbSet<SportImage> SportImages { get; set; }
        public DbSet<Sport> Sports { get; set; }
        public DbSet<TeamColor> TeamColors { get; set; }
        public DbSet<TeamImage> TeamImages { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<zPlayer> zPlayers { get; set; }
    }
}
