//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickerTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class zPlayer
    {
        public Nullable<int> ID { get; set; }
        public Nullable<short> TeamID { get; set; }
        public Nullable<short> LeagueID { get; set; }
        public Nullable<int> LinkID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DisplayName { get; set; }
        public string Character { get; set; }
        public string AlternateCharacter { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> PrimaryPosition { get; set; }
        public Nullable<int> BattingOrder { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public bool Pitcher { get; set; }
        public bool Rookie { get; set; }
        public bool LeftHanded { get; set; }
        public bool RightHanded { get; set; }
        public bool PinchHitter { get; set; }
        public string HitZone { get; set; }
        public Nullable<int> Jersey { get; set; }
        public string DisplayJersey { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> Throws { get; set; }
        public Nullable<int> Bats { get; set; }
        public Nullable<int> Revision { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public bool AllStar { get; set; }
        public Nullable<int> Eligibility { get; set; }
        public string TwitterHandle { get; set; }
    }
}
